### ISSUE TITLE
[JOSS Review] The software paper

### ISSUE THREAD

**Issue by simone-silvestri** [gaelforget/MITgcm.jl#104]
@gaelforget the paper is well-written, I have just a minor comment on figure 2 which I believe is not very descriptive of the user interface. Would it be possible to show the interface that actually runs (or builds) the model instead of the description of what the notebook does?

**Comment by gaelforget** [comment]
Done in commit https://github.com/gaelforget/MITgcm.jl/commit/7f9877117a00ba67921324999c24ae7a56a9084e

See latest build at https://github.com/openjournals/joss-reviews/issues/6710#issuecomment-2187117429

Works?

**Comment by simone-silvestri** [comment]
looks good!
