### ISSUE TITLE
[JOSS Review] Documentation

### ISSUE THREAD

**Issue by simone-silvestri** [gaelforget/MITgcm.jl#105]
As for the paper, it is written and descriptive. I have a couple of comments

- The first mention of MITgcm.jl is in the MITgcm File Formats section using MITgcm_tutorial_global_oce_biogeo.jl. However, this notebook is not found in the examples. I believe it would be better to showcase an example from the repository, like the one shown below with MITgcm_scan_output.jl.
- While it is nice to have notebooks, I think it would be beneficial to include an example that runs in the terminal.
- (Maybe a lot of work so not strictly necessary) At the moment the only literated example in the docs runs a simulation but does not show any visual output. Adding a visualization (using Plots or CairoMakie) to the examples in the documentation would greatly help non-MITgcm users (does not have to be a prognostic field, it could also be just the grid visualized on a sphere).

**Comment by gaelforget** [comment]
I think v0.4.2 adresses these three comments (thanks for the suggestion).

Can this issue can be closed based on the latest docs?
