### ISSUE TITLE
[JOSS Review] Repository

### ISSUE THREAD

**Issue by simone-silvestri** [gaelforget/MITgcm.jl#106]
1. I was able to run the example provided in https://gaelforget.github.io/MITgcm.jl/dev/examples/ on a Linux computer but not on my Mac M1. After some investigation, most likely it was a problem with the optfile for Apple silicon that was recently changed (probably after https://github.com/MITgcm/MITgcm/pull/613). Eventually, I was able to run the `advect_xy` configuration by specifying a NETCDF_ROOT directory. However, the error message was not instructive so it was difficult to assess the problem. I would suggest more verbose error messages such that the user can diagnose what is wrong (or even report the error through an issue on this repo)
2. A couple of bugs in the `MITgcm_scan_output.jl` example:
- When selecting the ECCO grid the error is `UndefVarError: Point2 not defined`
- When selecting the verification grid I get `type Missing has no field params_files` (I think it refers to the variable sc)
3. `MITgcm.jl_run` example: the only case that runs is the `advect_xy`, all the other configurations fail to build with the error `model compilation may have failed`
4. MITgcm_workflow.jl` example: 
- The `advect_xy` configuration runs and shows a visualization of the results. 
- The other cases fail with the error message `KeyError: key :setup not found`
6. I have problems with building other examples such as `HS94_animation.jl` 
7. Given that most of the examples do not work on my laptop, I think it might be a configuration issue from my side. Providing a non-pluto example that produces a headless visualization (such as with CairoMakie) would help me test the repo on a remote linux machine.
8. as written in #105 (and given point 7.) I would add an example that runs in the terminal (for non-GUI people like myself) so that it is not necessary to open Pluto which requires a graphical user interface

**Comment by gaelforget** [comment]
> 1. I was able to run the example provided in https://gaelforget.github.io/MITgcm.jl/dev/examples/ on a Linux computer but not on my Mac M1. After some investigation, most likely it was a problem with the optfile for Apple silicon that was recently changed (probably after [new build-options file for darwin arm64 MITgcm/MITgcm#613](https://github.com/MITgcm/MITgcm/pull/613)). 

Sorry for this! I had not updated the default version of MITgcm that MITgcm.jl uses. Should work now with MITgcm.jl v0.4.0 that uses MITgcm-checkpoint68.

> Eventually, I was able to run the `advect_xy` configuration by specifying a NETCDF_ROOT directory. However, the error message was not instructive so it was difficult to assess the problem. I would suggest more verbose error messages such that the user can diagnose what is wrong (or even report the error through an issue on this repo)

The NETCDF_ROOT issue seems to come from MITgcm itself, and maybe there's a bug with the genmake2 script that creates the Makefile. 

Found these two issue : https://github.com/MITgcm/MITgcm/issues/82 & https://github.com/MITgcm/MITgcm/issues/635 . I believe there was some explanation about NETCDF_ROOT in the documentation but strangely that seems to have been cut, making things worse.

Like you, I find that I need NETCDF_ROOT defined to build the verification examples. But even if I do (line below that matches what I see in `nc-config --all`) then genmake2 turns off mnc (the package that would generated netcdf files). The examples run but generate binary output.

`export NETCDF_ROOT='/opt/homebrew/Cellar/netcdf/4.9.2_1/'

And If undefined NETCDF_ROOT then we end up with an incorrect Makefile that has :

`LIBS = -L/opt/homebrew/Cellar/netcdf-fortran/4.6.1/lib -lnetcdff -lnetcdf -lnetcdf`

**Comment by simone-silvestri** [comment]
> Sorry for this! I had not updated the default version of MITgcm that MITgcm.jl uses. Should work now with MITgcm.jl v0.4.0 that uses MITgcm-checkpoint68.

Thanks, then I'll try again after updating the repo and setting the `NETCDF_ROOT` flag

**Comment by gaelforget** [comment]
> 2 A couple of bugs in the MITgcm_scan_output.jl example:
When selecting the ECCO grid the error is UndefVarError: Point2 not defined
When selecting the verification grid I get type Missing has no field params_files (I think it refers to the variable sc)

Should be fixed after https://github.com/gaelforget/MITgcm.jl/pull/108 and https://github.com/gaelforget/MITgcm.jl/pull/109

**Comment by gaelforget** [comment]
> 3 MITgcm.jl_run example: the only case that runs is the advect_xy, all the other configurations fail to build with the error model compilation may have failed

Should be fixed (using v0.4.0 of MITgcm.jl + https://github.com/gaelforget/MITgcm.jl/pull/110)

**Comment by gaelforget** [comment]
> 4 MITgcm_workflow.jl` example:
The advect_xy configuration runs and shows a visualization of the results.
The other cases fail with the error message KeyError: key :setup not found

Should be fixed (using v0.4.0 of MITgcm.jl, NETCDF_ROOT -- to support ARM laptops)

**Comment by gaelforget** [comment]
> 7 Given that most of the examples do not work on my laptop, I think it might be a configuration issue from my side. Providing a non-pluto example that produces a headless visualization (such as with CairoMakie) would help me test the repo on a remote linux machine.
> 8 as written in https://github.com/gaelforget/MITgcm.jl/issues/105 (and given point 7.) I would add an example that runs in the terminal (for non-GUI people like myself) so that it is not necessary to open Pluto which requires a graphical user interface

Will address this @ https://github.com/gaelforget/MITgcm.jl/issues/105

Good points!

**Comment by gaelforget** [comment]
> 7 Given that most of the examples do not work on my laptop,

Hi @simone-silvestri 

About building on your laptop, can you try with `export NETCDF_ROOT=/opt/homebrew` ?

This fixed it for me.

See jahn's suggestion @ https://github.com/MITgcm/MITgcm/issues/846#issuecomment-2181691225

**Comment by simone-silvestri** [comment]
Thanks @gaelforget, today I ll test the changes and update you

**Comment by gaelforget** [comment]
Great! Thank you

ps. I am about to release v0.4.1 

- includes ```MITgcm.set_environment_variables_to_default``` as a basic way to define `NETCDF_ROOT` and `MPI_INC_DIR`
- to be improved later ...

**Comment by gaelforget** [comment]
> Given that most of the examples do not work on my laptop, I think it might be a configuration issue from my side. Providing a non-pluto example that produces a headless visualization (such as with CairoMakie) would help me test the repo on a remote linux machine.

done

ps. about _configuration issue from my side_, I had the same issue. see https://github.com/MITgcm/MITgcm/issues/846 

> as written in https://github.com/gaelforget/MITgcm.jl/issues/105 (and given point 7.) I would add an example that runs in the terminal (for non-GUI people like myself) so that it is not necessary to open Pluto which requires a graphical user interface

done

ps. I don't think that running Pluto notebooks requires a graphical user interface. In a terminal window, or batch, `using Pluto; Pluto.activate_notebook_environment("nb.jl"); include(nb.jl)` as well as `PlutoSliderServer.export_notebook("nb.jl") should work.

**Comment by gaelforget** [comment]
All set of this issue (1 to 8)?

**Comment by gaelforget** [comment]
Hi @simone-silvestri 

quick bump. I should be able to work on this next week if needed, unless we are ready to close this one?

**Comment by gaelforget** [comment]
> 6 I have problems with building other examples such as HS94_animation.jl

Issue remained which should be fixed in https://github.com/gaelforget/MITgcm.jl/pull/123

**Comment by simone-silvestri** [comment]
Here are the output of running the examples of two different machines.
all the examples are run by setting
```julia
julia> using Pluto

julia> Pluto.activate_notebook_environment("examples/example.jl")

(example.jl) pkg> instantiate
```

# Macbook pro, M1

### MITgcm_configurations

Runs!

### MITgcm_workflow.jl

```Julia
julia> include("examples/MITgcm_worklow.jl")
ERROR: LoadError: KeyError: key :setup not found
Stacktrace:
 [1] getindex
   @ ~/.julia/packages/OrderedCollections/9C4Uz/src/ordered_dict.jl:385 [inlined]
 [2] build(config::MITgcm_config)
   @ MITgcm ~/.julia/packages/MITgcm/apnJ2/src/ModelSteps.jl:32
 [3] top-level scope
   @ ~/development/MITgcm.jl/examples/MITgcm_worklow.jl:89
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [5] top-level scope
   @ REPL[10]:1
in expression starting at /Users/loaner/development/MITgcm.jl/examples/MITgcm_worklow.jl:87
```

### MITgcm_run.jl

Failed for an unspecified reason

```julia
(MITgcm_run.jl) pkg> instantiate

julia> include("examples/MITgcm_run.jl")
model compilation may have failed
"# This file is machine-generated - editing it directly is not advised\n\njulia_version = \"1.10.4\"\nmanifest_format = \"2.0\"\nproject_hash = \"78ba067645459166fe1dc27b5aa25fa01a547b1c\"\n\n[[deps.AbstractPlutoDingetjes]]\ndeps = [\"Pkg\"]\ngit-tree-sha1 = \"6e1d2a35f2f90a4bc7c2ed98079b2ba09c35b83a\"\nuuid = \"6e696c72-6542-2067-7265-42206c756150\"\nversion = \"1.3.2\"\n\n[[deps.ArgTools]]\nuuid = \"0dad84c5-d112-42e6-8d28-ef12dabb789f\"\nversion = \"1.1.1\"\n\n[[deps.A" ⋯ 20614 bytes ⋯ "[\"Libdl\"]\nuuid = \"83775a58-1f1d-513f-b197-d71354ab007a\"\nversion = \"1.2.13+1\"\n\n[[deps.libblastrampoline_jll]]\ndeps = [\"Artifacts\", \"Libdl\"]\nuuid = \"8e850b90-86db-534c-a0d3-1478176c7d93\"\nversion = \"5.8.0+1\"\n\n[[deps.nghttp2_jll]]\ndeps = [\"Artifacts\", \"Libdl\"]\nuuid = \"8e850ede-7688-5339-a07c-302acd2aaf8d\"\nversion = \"1.52.0+1\"\n\n[[deps.p7zip_jll]]\ndeps = [\"Artifacts\", \"Libdl\"]\nuuid = \"3f19e933-33d8-53b3-aaab-bd5110c3b7a0\"\nversion = \"17.4.0+2\"\n"
```

### MITgcm_scan_output.jl

Runs!

### HS94_animation.jl

```julia
julia> include(“examples/HS94_animation.jl”)
ERROR: LoadError: UndefVarError: `PICKUP_hs94_path` not defined
Stacktrace:
 [1] top-level scope
   @ ~/development/MITgcm.jl/examples/HS94_animation.jl:78
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [3] top-level scope
   @ REPL[4]:1
in expression starting at /Users/loaner/development/MITgcm.jl/examples/HS94_animation.jl:78
```

### Other HS94 examples

Did not try them because contingent on `HS94_animation.jl` to complete

# Ubuntu 20.04.6 LTS

### MITgcm_configurations

Runs!

### MITgcm_workflow.jl

```julia
julia> include("examples/MITgcm_worklow.jl")
ERROR: LoadError: KeyError: key :setup not found
Stacktrace:
 [1] getindex
   @ ~/.julia/packages/OrderedCollections/9C4Uz/src/ordered_dict.jl:385 [inlined]
 [2] build(config::MITgcm_config)
   @ MITgcm ~/.julia/packages/MITgcm/apnJ2/src/ModelSteps.jl:32
 [3] top-level scope
   @ ~/development/MITgcm.jl/examples/MITgcm_worklow.jl:89
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [5] top-level scope
   @ REPL[10]:1
in expression starting at /Users/loaner/development/MITgcm.jl/examples/MITgcm_worklow.jl:87
```

### MITgcm_run.jl

Runs!

### MITgcm_scan_output.jl

Runs!

### HS94_animation.jl

Runs! 

### HS94_particles.jl

Cannot find the output of `HS94_animation.jl`

```julia
julia> include("examples/HS94_particles.jl")
ERROR: LoadError: IOError: readdir("/home/ssilvest/.julia/scratchspaces/dce5fa8e-68ce-4431-a242-9469c69627a0/src/pickup_hs94.cs-32x32x5/run/"): no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error
   @ ./libuv.jl:100 [inlined]
 [2] readdir(dir::String; join::Bool, sort::Bool)
   @ Base.Filesystem ./file.jl:869
 [3] readdir
   @ ./file.jl:862 [inlined]
 [4] GridLoad(γ::gcmgrid; option::String)
   @ MeshArrays ~/.julia/packages/MeshArrays/k45D3/src/Grids.jl:245
 [5] top-level scope
   @ ~/development/MITgcm.jl/examples/HS94_particles.jl:59
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [7] top-level scope
   @ REPL[8]:1
in expression starting at /home/ssilvest/development/MITgcm.jl/examples/HS94_particles.jl:56
```

The output of that scratchspace is
```julia
shell> ls /home/ssilvest/.julia/scratchspaces/dce5fa8e-68ce-4431-a242-9469c69627a0/src/
MITgcm-checkpoint68y

shell> ls /home/ssilvest/.julia/scratchspaces/dce5fa8e-68ce-4431-a242-9469c69627a0/src/MITgcm-checkpoint68y/
doc  eesupp  LICENSE.txt  model  pkg  README.md  tools	verification
```

### HS94_Makie.jl

same as above

## Conclusion

It looks like there is a problem with `MITgcm_run.jl` on the Macbook, but that is probably a system issue on my laptop since the example runs on the linux system. 
The same for `HS94_animation.jl`. It runs on the linux system but it seems to have some pathing problem on the macbook. 
For the examples dependent on `HS94_animation.jl` I could test only on the linux system and I am not sure what is happening but there seem to be an issue with the pathing.

**Comment by simone-silvestri** [comment]
I have tried the new version on the linux machine, and I am happy to say that all most the examples that were not running before (`MITgcm_worflow.jl` as well as the `HS94` series) seem to work. 

Only two issues to solve: 
- `plot_xy` in `HS94_particles.jl` is defined _after_ it is called, so I had to move it up to make sure it is defined before the first use.
- In `HS94_Makie.jl` these lines
```julia
        lo = @lift(rec_by_t[$time].lon)
        la = @lift(rec_by_t[$time].lat)

        fi1,ax1 = scatter(lo, la, markersize = 4.0, color=:blue, strokewidth = 0.0)
        xlims!(ax1,(-180.,180.)); ylims!(ax1,(-90.,90.))
```
 spit out the error:
```julia
julia> include("examples/HS94_Makie.jl")
ERROR: LoadError: Cannot convert Observable{SubArray{Float64, 1, Vector{Float64}, Tuple{Vector{Int64}}, false}} to series data for plotting
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] _prepare_series_data(x::Observable{SubArray{Float64, 1, Vector{Float64}, Tuple{Vector{Int64}}, false}})
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/BGM3l/src/series.jl:8
  [3] _series_data_vector(x::Observable{SubArray{Float64, 1, Vector{Float64}, Tuple{Vector{…}}, false}}, plotattributes::Dict{Symbol, Any})
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/BGM3l/src/series.jl:36
  [4] macro expansion
    @ ~/.julia/packages/RecipesPipeline/BGM3l/src/series.jl:128 [inlined]
  [5] apply_recipe(plotattributes::AbstractDict{Symbol, Any}, ::Type{RecipesPipeline.SliceIt}, x::Any, y::Any, z::Any)
    @ RecipesPipeline ~/.julia/packages/RecipesBase/BRe07/src/RecipesBase.jl:300
  [6] _process_userrecipes!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/BGM3l/src/user_recipe.jl:38
  [7] recipe_pipeline!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/BGM3l/src/RecipesPipeline.jl:72
  [8] _plot!(plt::Plots.Plot, plotattributes::Any, args::Any)
    @ Plots ~/.julia/packages/Plots/du2dt/src/plot.jl:223
  [9] plot(::Any, ::Vararg{Any}; kw...)
    @ Plots ~/.julia/packages/Plots/du2dt/src/plot.jl:102
 [10] scatter(::Any, ::Vararg{Any}; kw...)
    @ Plots ~/.julia/packages/RecipesBase/BRe07/src/RecipesBase.jl:427
 [11] top-level scope
    @ ~/development/MITgcm.jl/examples/HS94_Makie.jl:43
 [12] include(fname::String)
    @ Base.MainInclude ./client.jl:489
 [13] top-level scope
    @ REPL[43]:1
in expression starting at /home/ssilvest/development/MITgcm.jl/examples/HS94_Makie.jl:36
Some type information was truncated. Use `show(err)` to see complete types.

```

However, these issues are not directly related with the repository and are most likely very easy to solve. So I can close this issue and mention on https://github.com/openjournals/joss-reviews/issues/6710 that my review is completed.
