### ISSUE TITLE
[JOSS Review] Minor comments

### ISSUE THREAD

**Issue by swilliamson7** [gaelforget/MITgcm.jl#128]
Hello! I've gone through the examples and such, and really only have minor comments. 

1. The first is that `HS94_Makie.jl` didn't run for me. I get the error message 
```julia
ArgumentError: No file exists at given path: /var/folders/7h/kw60pdp92yv7z_x6hjb4b0mr0000gq/T/HS94_animation_link/run/HS94.jld2
```
when trying to run the Pluto notebook

2. The second, and really minor, is that in the documentation when looking through "Functionalities" a couple functions are listed as `ClimateModels.function` where they should be `MITgcm.function`, if that make sense. These are specifically the functions `build`, `clean`, `compile`, and `setup`. 

Aside from those I didn't run into issues running the code/examples given. I have some thoughts on the documentation itself, but don't feel that this should prevent the paper from being published so maybe take the remainder as "potential considerations for future versions of the documentation" :) 

I really like `MITgcm_workflow.jl` and `HS94_animation.jl`, since they both provide a good walkthrough of how to run specific model configurations and read the output. I do think that it would be helpful though to provide a bit more info on what's going on. 

For example, in `MITgcm_workflow.jl` when we get to analyzing results the user is shown a list of (what I think are all) outputs from running the configuration, in my case this was `tutorial_global_oce_biogeo`. However _what_ the variables are is sort of vague, I don't really know what's contained in something like `"surfDiag.0005184004.001.002.data"` and it could be useful to have a reference point on what exactly I'm looking at/what the MITgcm returns to the user. I'm guessing that this is all documented in the MITgcm documentation itself, so maybe providing a link to the relevant location? 

Going to `HS94_animation.jl`, I have a somewhat similar comment. In the block on Workflow Steps, we're shown sort of three things. First we setup the directory, then compile, and then how to modify parameters. Setting up the directory and compiling the model is fine since this is, I'm guessing, fairly uniform across the different configurations, but the tunable parameters likely change between model configurations. It could be helpful to describe to the user what options they have, so again just a link to the MITgcm documentation and/or providing an explanation here. It’s also still not overly clear to me how one goes about changing parameters. In this example I can piece together what was done, but for example in the line 

`fil1=joinpath(PICKUP_hs94_path,"pickup.0000043200.data”)`

I don’t know where the path `PICKUP_hs94_path` came from, or how we knew that this is how to adjust the initial state. 

I guess in summary, providing information on the MITgcm and what capabilities it has, especially considering there will be people who come to use `MITgcm.jl` who (like me) have never used the MITgcm before. So reading pickups and building models are all sort of foreign concepts when you’re used to Julia ocean models. As a bit of a side note, it would also be really cool if there was an example that demonstrated the adjoint capabilities the MITgcm (ECCO?) has. I’m guessing this would be computationally expensive, but still really neat to see in Julia.

**Comment by gaelforget** [comment]
cross-linking : https://github.com/openjournals/joss-reviews/issues/6710

**Comment by gaelforget** [comment]
Thanks @swilliamson7 for the very useful feedback.

> 1. The first is that HS94_Makie.jl didn't run for me. I get the error message

The reason for this is that the 3 `HS94*jl` tutorials need to be run in sequence. This is indicated in the docs but, within each notebook, the error message you get is not sufficient. 

in https://github.com/gaelforget/MITgcm.jl/pull/130 

I added switches to by pass running the code cells that would error out + a message that provides users direction on the notebooks they need to run first. I added another warning in the docs about this too.

**Comment by gaelforget** [comment]
> 2. The second, and really minor, is that in the documentation when looking through "Functionalities" a couple functions are listed as ClimateModels.function where they should be MITgcm.function, if that make sense. These are specifically the functions build, clean, compile, and setup.

I am not sure that this is an issue to fix, as these are methods that are imported from ClimateModels.jl and are specialized for MITgcm here. Also the `source` code links point to the right code within `MITgcm.jl`.

With this said, I added a statement that _The following three methods implement the [ClimateModels.jl](https://github.com/gaelforget/ClimateModels.jl/#readme)'s interface for [MITgcm](https://github.com/MITgcm/MITgcm#readme)._ just before these doc strings in the online docs.

In PR tbd ...

**Comment by gaelforget** [comment]
> I really like MITgcm_workflow.jl and HS94_animation.jl, since they both provide a good walkthrough of how to run specific model configurations and read the output. I do think that it would be helpful though to provide a bit more info on what's going on.

Great to hear! Thank you!!

> For example, in MITgcm_workflow.jl when we get to analyzing results the user is shown a list of (what I think are all) outputs from running the configuration, in my case this was tutorial_global_oce_biogeo. However what the variables are is sort of vague, I don't really know what's contained in something like "surfDiag.0005184004.001.002.data" and it could be useful to have a reference point on what exactly I'm looking at/what the MITgcm returns to the user. I'm guessing that this is all documented in the MITgcm documentation itself, so maybe providing a link to the relevant location?

will do

> Going to HS94_animation.jl, I have a somewhat similar comment. In the block on Workflow Steps, we're shown sort of three things. First we setup the directory, then compile, and then how to modify parameters. Setting up the directory and compiling the model is fine since this is, I'm guessing, fairly uniform across the different configurations, but the tunable parameters likely change between model configurations. It could be helpful to describe to the user what options they have, so again just a link to the MITgcm documentation and/or providing an explanation here. It’s also still not overly clear to me how one goes about changing parameters. In this example I can piece together what was done, but for example in the line
> 
> fil1=joinpath(PICKUP_hs94_path,"pickup.0000043200.data”)
> 
> I don’t know where the path PICKUP_hs94_path came from, or how we knew that this is how to adjust the initial state.

will do

**Comment by gaelforget** [comment]
> I guess in summary, providing information on the MITgcm and what capabilities it has, especially considering there will be people who come to use MITgcm.jl who (like me) have never used the MITgcm before. 

agreed

> So reading pickups and building models are all sort of foreign concepts when you’re used to Julia ocean models. 

I tend to think that it's not so different -- initial conditions might be in jld2, and the build step via a constructor in Julia. That's the thinking behind the design of [ClimateModels.jl](https://github.com/gaelforget/ClimateModels.jl#readme).

> As a bit of a side note, it would also be really cool if there was an example that demonstrated the adjoint capabilities the MITgcm (ECCO?) has. I’m guessing this would be computationally expensive, but still really neat to see in Julia.

Agreed, but if that's ok I'd like to separate this out as an issue for later. Adjoint examples are in fact listed in https://github.com/gaelforget/MITgcm.jl/issues/117 with other features that I feel could be good to add.

**Comment by gaelforget** [comment]
Maybe we are ready to close this issue? Please let me know

**Comment by swilliamson7** [comment]
Yes, issue can be closed! Sorry that my first comment was just me missing instructions 😅

**Comment by gaelforget** [comment]
> Yes, issue can be closed! 

Cool!

> Sorry that my first comment was just me missing instructions 😅

Not at all. It's helped improve the notebooks & was totally fair comment. Thank you again
